'''src/agents/error_classifier.py'''
"""Utility module for classifying agent execution errors and providing repair hints.

The function :func:`classify_error` receives the raw exception message generated by an
agent's execution loop together with the code that caused the failure. It analyses the
message using a small set of regular‑expression patterns and returns a deterministic
dictionary that the orchestrator can use to decide whether the error is recoverable
and what kind of transformation request should be issued.

The returned dictionary has the following keys:

* ``category`` – a short, machine‑readable label (e.g. ``type_coercion``,
  ``missing_column``, ``nan_values``).
* ``recoverable`` – ``True`` if the orchestrator can automatically attempt a
  repair via :class:`TransformationAgent`; ``False`` otherwise.
* ``repair_hint`` – a concise natural‑language instruction that can be passed to
  the transformation agent. It is optional for non‑recoverable errors.
* ``details`` – any additional extracted information that may be useful for
  debugging or for richer UI messages.
"""

import re
from typing import Dict, Any


def _extract_column_from_message(message: str) -> str:
    """Attempt to pull a column name from common pandas/NumPy error messages.

    The heuristics cover patterns like:
    * "could not convert string to float: 'abc'" – column is unknown, but the
      offending value is shown, which we surface as ``unknown_column``.
    * "column 'age' does not exist" – direct column name extraction.
    * "cannot mask with non‑boolean array containing NA / NaN values" – we treat as
      ``nan_values`` with no specific column.
    """
    # Pattern for "column 'name'" (single quotes)
    col_match = re.search(r"column ['\"]([^'\"]+)['\"]", message, re.IGNORECASE)
    if col_match:
        return col_match.group(1)
    # Pattern for conversion errors that include the offending value
    val_match = re.search(r"could not convert string to (?:float|int): '([^']+)'", message)
    if val_match:
        # The value itself doesn't give us the column, return a placeholder
        return "unknown_column"
    return ""


def classify_error(error_message: str, code: str) -> Dict[str, Any]:
    """Classify an execution error and generate a repair hint.

    The function is deliberately lightweight – it avoids any heavy LLM calls and
    works purely on string heuristics, making it suitable for the local‑only
    deployment model of this project.
    """
    lowered = error_message.lower()
    result: Dict[str, Any] = {
        "category": "unknown",
        "recoverable": False,
        "repair_hint": "",
        "details": {},
    }

    # 1️⃣ Type coercion errors (e.g. trying to plot strings as numbers)
    if "could not convert" in lowered or "invalid literal" in lowered or "float" in lowered:
        col = _extract_column_from_message(error_message)
        result["category"] = "type_coercion"
        result["recoverable"] = True
        if col and col != "unknown_column":
            result["repair_hint"] = f"Convert column '{col}' to a numeric type (e.g. using pd.to_numeric)."
        else:
            result["repair_hint"] = "Convert appropriate columns to numeric types."
        result["details"]["column"] = col
        return result

    # 2️⃣ Missing column / attribute errors
    if "does not exist" in lowered or "key error" in lowered:
        col = _extract_column_from_message(error_message)
        result["category"] = "missing_column"
        result["recoverable"] = False
        result["details"]["column"] = col
        return result

    # 3️⃣ NaN / missing value errors during masking or calculations
    if "nan" in lowered or "null" in lowered or "missing" in lowered:
        if "cannot mask" in lowered or "must not contain na" in lowered:
            result["category"] = "nan_values"
            result["recoverable"] = True
            result["repair_hint"] = "Fill missing values (e.g., with 0 or the column mean) before proceeding."
            return result

    # 4️⃣ General execution errors that are unlikely to be auto‑fixed
    result["category"] = "general_execution"
    result["recoverable"] = False
    return result


__all__ = ["classify_error"]
